### ISSUE TITLE
Feature Request - Can we add an option to have Related link when we use the button.  

### ISSUE THREAD

**Issue by pooja2289** [avih75/TFS_Action_Button#13]
Hi @avih75 - This is a feature request if we could have an option to relate a work item like we have to create a Child link option. 
Below is what we are using this plugin for: 

1. Create a Hotfix Workitem (This is a new Work item) which we have created internally. 
![image](https://user-images.githubusercontent.com/22241401/107280575-82c23800-6a26-11eb-8e0e-4b6b8d4cfa6c.png)

2. Then we are using the Action Control button on that Work item to the "Create a Copy" ticket. 
![image](https://user-images.githubusercontent.com/22241401/107280822-d3399580-6a26-11eb-8a78-fdd6bf81e4fb.png)

3. Once the Copy is created it becomes a "Child" link and the "Hotfix" becomes the Parent. 

4. If I remove the option of creating a Child Link from the Action control button editor, and then try to use the "Create a Copy" button the copy ticket doesn't get displayed on the screen. It just displays the pop-up. 
![image](https://user-images.githubusercontent.com/22241401/107280966-0b40d880-6a27-11eb-9b92-ef334a55cd84.png)

5. But, If I have the Child link enabled, the Copy Work Item gets displayed on the screen. 
![image](https://user-images.githubusercontent.com/22241401/107281115-4216ee80-6a27-11eb-8d0a-fc25f95e6454.png)

My request is - Can you provide an option to make this related link like we have the option to create a Child Link or be able to display the Copy Work item even though we don't enable creating Child Link.

**Comment by avih75** [comment]
it have an option to add link type to it

**Comment by avih75** [comment]
thank you
