### ISSUE TITLE
Options screen, Tooltips Typo

### ISSUE THREAD

**Issue by FormidableYeti** [avih75/TFS_Action_Button#8]
Options screen tooltip for fields indicates fields to be separated by semicolon.  Actual requires comma.  Just a quick typo correction for this one.

![cab9](https://user-images.githubusercontent.com/76529511/103156937-99147d00-4773-11eb-903f-08154f42feab.jpg)

**Comment by avih75** [comment]
Got a point

בתאריך שבת, 26 בדצמ׳ 2020, 20:13, מאת FormidableYeti ‏<
notifications@github.com>:

**Comment by FormidableYeti** [comment]
I show this as fixed, thank you!
