### ISSUE TITLE
Feature Request - Customize Copied Ticket Name

### ISSUE THREAD

**Issue by FormidableYeti** [avih75/TFS_Action_Button#9]
Feature request.

In the options screen, add an option to customize the copied ticket title.   

Perhaps:
option name:  Prepend Text to New Ticket Title:
tool tip: text in this option will be added to the beginning of copied ticket title.
optional/required:  optional

Functionality:

Prepend text + (space for formatting) + ParentTicketTitle

Example - Original ticket title "Test ticket"     
Options field "Prepend Text to Title" = Copy of
Created ticket Title = "Copy of Test ticket"

**Comment by avih75** [comment]
Good idea

בתאריך שבת, 26 בדצמ׳ 2020, 20:49, מאת FormidableYeti ‏<
notifications@github.com>:

**Comment by FormidableYeti** [comment]
Yes, amazing add.  Thank you for putting this into the code.
